### ISSUE TITLE
Project had an error (No example though)

### ISSUE THREAD

**Issue by mihkell** [mdgriffith/elm-optimize-level-2#97]
Again due to the fact that project timeline is tight can't make an example, but in my project it started to say to give negative values for AnyDict.all function.

**Comment by mihkell** [comment]
Had another error. Not much use without example, but it would take at current time too much of my time to produce an example. (Start-up needs building =D) 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'ah')
    at NT (main.js:1:148129)
    at main.js:1:148362
    at main.js:1:148062
    at Hp (main.js:1:94619)
    at IT (main.js:1:148037)
    at main.js:1:148316
    at Kp (main.js:1:94324)
    at TT (main.js:1:148211)
    at FT (main.js:1:148664)
    at VT (main.js:1:149949)
```
